Добавить матрицы и простейшие операции с ними
UnrealEugene/math_parser pull request #21
Opened 2020-08-01 10:10 UTC by UnrealEugene

- [ ] Матрицы `math::matrix`
---
Простейшие операции:
- [ ] Сложение `+`
- [ ] Умножение `*`
- [ ] Транспонирование `transpose`
---
- [ ] Скалярное произведение
- [ ] Векторное произведение
---
Усложненные операции:
- [ ] Вычисления определителя

2020-08-01 10:12 UTC, UnrealEugene commented
В предыдущем коммите также были изменены имена, так как матрицы не назовёшь числом: 
* `math::value` -> `math::constant`
* `math::number` -> `math::value`

2020-08-01 11:11 UTC, boorlakov requested changes
Отлично, только выгоднее сделать матрицу как вектор векторов.

2020-08-01 12:59 UTC, boorlakov requested changes
Маленькая стиль ремарка, а так всё отлично!

2020-08-01 12:59 UTC, boorlakov commented on expression/utility/value.h
> +        };
```suggestion
    private:
        struct base_holder_ {
            virtual ~base_holder_() = default;
            virtual std::type_info const& type_info_() const = 0;
        };

        template <typename T>
        struct holder_ : base_holder_ {
            explicit holder_(T const& t) : t_(t) { }
            std::type_info const& type_info_() const override {
                return typeid(t_);
            }

            T t_;
        };
```
11. Членам класса с модификатором private следует присваивать суффикс-подчёркивание.
[Источник](https://tldrify.com/zjv).

В остальном же всё прекрасно, я доволен!

2020-08-05 10:22 UTC, boorlakov approved these changes
Отлично!

2020-08-05 10:29 UTC, boorlakov approved these changes
Прекрасно! 👍

2020-08-05 10:31 UTC, merged